# Generated by Django 3.0.4 on 2020-04-03 16:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 3, 16, 39, 13, 219268, tzinfo=utc)),
        ),
    ]
