# Generated by Django 3.0.4 on 2020-04-04 13:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200403_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 4, 13, 42, 5, 597498, tzinfo=utc)),
        ),
    ]
