# Generated by Django 3.0.4 on 2020-04-05 10:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200405_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 5, 10, 55, 9, 735245, tzinfo=utc)),
        ),
    ]
