# Generated by Django 3.0.4 on 2020-04-05 14:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200405_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 5, 14, 42, 26, 207552, tzinfo=utc)),
        ),
    ]
